---
# Basic healthcheck of the kaiju server.
# Run: ansible-playbook -i ../inventory/hosts.yml playbooks/healthcheck-basic.yml

- name: Basic healthcheck for kaiju
  hosts: kaiju
  become: true

  tasks:
    - name: Run basic healthcheck tasks
      ansible.builtin.import_tasks: healthcheck-basic-tasks.yml

